image: docker:latest
services:
  - docker:dind
stages:
  - build

docker:
  stage: build
  artifacts:
    paths:
      - dist/linux/autosshpy
      - dist/linux/tmuxpy
  script:
    - docker run -v "$(pwd):/src/" cdrx/pyinstaller-linux
