{
    'bg': 'red',
    'fg': 'white',
    'windows': {
        'left': {
            'windows': {
                'python': {},
                'devops': {},
                'js': {},
                'mobile': {},
                'riak': {},
                'home': {}
            }
        },
        'right': {
            'windows': {
                'python_dev': {},
                'devops_dev': {},
                'js_dev': {},
                'mobile_dev': {},
                'riak_dev': {},
                'home_dev': {}
            }
        },
        'comm': {
            'windows': {
                'network': {},
                'system': {},
                'salt': {},
                'logs': {},
                'monitor': {}
            }
        },
        'test': {
            'windows': {
                'test_inner': {
                },
                'test2': {},
            }
        },
        'test_inner': {
            'windows': {
                'ping': {
                    'shell_command': 'ping google.com'
                },
                'htop': {
                    'shell_command': 'htop'
                }
            }
        }
    }
}
